# pae_compras/models/__init__.py

from .purchase_order import (
    PurchaseOrder,
    LineItem,
    OrderStatus,
    PurchaseOrderCreate,
    PurchaseOrderItem,
    PurchaseOrderResponse,
    MarkShippedResponse,
    CancelOrderRequest,
    CancelOrderResponse,
    PurchaseOrderFilters,
    PaginatedPurchaseOrderResponse,
    PurchaseOrderSummary,
)
from .provider import Provider
from .product import (
    Product, 
    WeeklyAvailability, 
    LifeTime, 
    ProductCreate, 
    ProductUpdate, 
    ProductResponse, 
    ProductListResponse
)
from .inventory import (
    Inventory,
    InventoryItem,
    InventoryItemResponse,
    InventoryConsultationQuery,
    InventoryConsultationResponse,
)
from .ingredient_receipt import (
    IngredientReceipt,
    IngredientReceiptBase,
    IngredientReceiptCreate,
    IngredientReceiptResponse,
    ReceivedItem,
)
from .inventory_movement import (
    InventoryMovement,
    MovementType,
    InventoryMovementResponse,
    InventoryConsumptionRequest,
    InventoryConsumptionResponse,
    BatchConsumptionDetail,
)
from .inventory_entry import (
    EntryMode,
    InventoryEntryItem,
    InventoryEntryRequest,
    InventoryEntryResponse,
    InventoryEntryValidationError,
    InventoryEntryValidationResponse,
    InventoryEntrySearchQuery,
    InventoryEntrySearchResponse,
    InventoryEntryStats,
)

__all__ = [
    "PurchaseOrder",
    "LineItem",
    "OrderStatus",
    "PurchaseOrderCreate",
    "PurchaseOrderItem",
    "PurchaseOrderResponse",
    "MarkShippedResponse",
    "CancelOrderRequest",
    "CancelOrderResponse",
    "PurchaseOrderFilters",
    "PaginatedPurchaseOrderResponse",
    "PurchaseOrderSummary",
    "Provider",
    "Product",
    "WeeklyAvailability",
    "LifeTime",
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductListResponse",
    "Inventory",
    "InventoryItem",
    "InventoryItemResponse",
    "InventoryConsultationQuery",
    "InventoryConsultationResponse",
    "IngredientReceipt",
    "IngredientReceiptBase",
    "IngredientReceiptCreate",
    "IngredientReceiptResponse",
    "ReceivedItem",
    "InventoryMovement",
    "MovementType",
    "InventoryMovementResponse",
    "InventoryConsumptionRequest",
    "InventoryConsumptionResponse",
    "BatchConsumptionDetail",
    "EntryMode",
    "InventoryEntryItem",
    "InventoryEntryRequest",
    "InventoryEntryResponse",
    "InventoryEntryValidationError",
    "InventoryEntryValidationResponse",
    "InventoryEntrySearchQuery",
    "InventoryEntrySearchResponse",
    "InventoryEntryStats",
]
